version: "3.7"
services:
  api:
    build: ./api
    command: "python3 -m gunicorn -b 0.0.0.0 --workers=2 --chdir .. api:new_app"
    expose:
      - 8000
    environment:
      INFURA_KEY: "e37c21b7a4e14c74b9719bea11d9d18f"
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - api
